### ISSUE TITLE
new assembly file doesn't get used in a precomputed outpath

### ISSUE THREAD

**Issue by chrisgulvik** [gregorysprenger/wf-ani#1]
### Description of the bug

Adding a new assembly file into a precomputed outdir path didn't modify/update the `comparisons/pairs.fofn` and the `comparisons/genomes.fofn` as expected, so no new pairs were computed.

### Command used and terminal output

```console
nextflow \
 -log /my-proj/ANI/assemblies.all-vs-all/nextflow_log.2898751.txt \
 run /workflows/wf-ani/main.nf \
 -w /scratch/work \
 --ani blast \
 -ansi-log false \
 -profile rosalind_hpc \
 --input /my-proj/all-assems \
 --outdir /my-proj/ANI/assemblies.all-vs-all \
 -resume
```
```


### Relevant files

_No response_

### System information

_No response_

**Comment by gregorysprenger** [comment]
Can you upload the nextflow_log file? Everything in the output directory should've been overwritten (whether it can find the cached files or not).
