### ISSUE TITLE
move nextflow_log to OUTDIR

### ISSUE THREAD

**Issue by chrisgulvik** [gregorysprenger/wf-ani#2]
### Description of feature

Currently the `nextflow_log.3160532.txt` just gets dumped into the current working directory. This should be placed into the outpath instead.

**Comment by gregorysprenger** [comment]
The `nextflow_log.*.txt` files are placed in the output directory when using the bash runner scripts. 

Only 2 possibilities for this to occur:
- You are running the nextflow command manually and setting the log file path
- You set the output directory for the bash runner scripts in to the current working directory
